# Generated by Django 2.2.2 on 2019-06-20 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sozlukContent', '0002_auto_20190619_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sozlukcontent',
            name='ekleyenId',
        ),
        migrations.AddField(
            model_name='sozlukcontent',
            name='ekleyenId',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
